name: build front

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_front:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: cd web
      - name: aaa
        run: npm run build
