name: build front

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: Enter the web dir
      run: cd ./web
    
    - name: Install node packages
      run: npm install
    
    - name: Build
      run: npm run build
